### PR TITLE
remove http prefix from img and link urls

### PR DESCRIPTION
**Pull request by rogy**

### CODE REVIEW

**Comment by buro9** [comment]
Deployed.

May need force refresh to see.

**Comment by rogy** [comment]
@buro9 doesnt appear to have pulled through still?

**Comment by buro9** [comment]
Works for me... try visiting https://www.lfgss.com/static/js/Markdown.Editor.js?v20160728 and CTRL+F5 on that.

**Comment by rogy** [comment]
Well thats done it! i hard refreshed the site a whole host of times. ta!

**Pull request merged**
